name = "Dileepkumar Adari"
rol = "Software Developer"
email = "adaridileep@gmail.com"
phone = "+91 7330701217"
birthday = "May 14, 2004"
location = "Vadrapalli, Visakhapatnam, India"
avatar = "./config/assets/avatars/delhi.jpg"
username = "Dileepadari"
googlemaps = "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1901.3545306725555!2d83.0014085889!3d17.61654515225135!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3a3973f2b7aea65f%3A0xd510b7cc2ba90dec!2sVadrapalli%2C%20Andhra%20Pradesh%20531033!5e0!3m2!1sen!2sin!4v1719320135410!5m2!1sen!2sin"
presentation = """
A passionate web developer and programmer. My journey revolves around the enchanting world of software engineering, where I thrive on turning ideas into reality through the art of coding. With a keen interest in crafting digital solutions, my focus is on creating seamless and innovative experiences. Welcome to my portfolio, where every line of code tells a story of creativity and precision in the realm of web development
"""
