[[post]]
category = "Extension"
title = "Virtual Labs Vscode Web Extension"
subtitle = "Reflecting on Building the VS Code Web Extension: A Student's Journey"
datetime = "2024-03-20"
image = "./config/assets/posts/vscode.jpeg"
url = "https://medium.com/@adaridileep/reflecting-on-building-the-vs-code-web-extension-a-students-journey-772936a7fbcc"