## I am a student in computer science engineering in 3rd year

[[doing]]
title = "FullStack Development"
icon = "./config/assets/icons/laptop-code.svg"
text = """
I have a strong foundation in web development and I am passionate about creating user-friendly and scalable web applications.
"""

[[doing]]
title = "Design Thinking"
icon = "./config/assets/icons/compass.svg"
text = """
Incorporating design principles and user-centric methodologies to create innovative and impactful solutions.
"""

[[doing]]
title = "UI/UX"
icon = "./config/assets/icons/mobile.svg"
text = """
Crafting intuitive and visually appealing user interfaces for web applications, focusing on usability, accessibility, and responsive design.
"""

[[doing]]
title = "Exploring Open Source"
icon = "./config/assets/icons/linux.svg"
text = """
Rebuilding open-source projects and college websites and exploring new technologies to enhance my skills and knowledge in software development.
"""