############## Education config #################
#################################################
[[education]]
title = "Vignan Institute of Technology and Science"
timeline = "Mar 2022 — Mar 2025"
description = "Bachelor of Technology - BTech, Mechanical Engineering"

[[education]]
title = "Rajiv Gandhi RECS Polytechnic College, Kasimkota"
timeline = "Jun 2019 — Mar 2022"
description = "Diploma of Education, Mechanical Engineering"

[[education]]
title = "AP Model School & Jr. College (APMS)"
timeline = "Jun 2014 — Mar 2019"
description = "10th SSC, Grade: 8.3"

[[education]]
title = "Prasanthi Nikethan M.V.V.S Murthy ENG MED School"
timeline = "Jun 2008 — Mar 2014"
description = "5th Class"

############## Experience config ################
#################################################
[[experience]]
title = "Mechanical Engineering Intern"
timeline = "Summer 2023"
description = "Internship at Royal Enfield, gaining hands-on experience in mechanical design, production processes, and quality control."

[[experience]]
title = "Mechanical Design Intern"
timeline = "Spring 2022"
description = "Internship at [Other Company Name], focusing on CAD modeling, prototyping, and testing of mechanical components."

[[experience]]
title = "Role Title"
timeline = "Start Year — End Year"
description = "Description of your role and responsibilities, highlighting key projects and achievements related to mechanical engineering."


############## Skills config ####################
#################################################
[skills]
title = "My Skills"
enabled = true
show_bar = true
show_value = true

[[skill]]
title = "CAD Modeling"
value = "85%"

[[skill]]
title = "Finite Element Analysis (FEA)"
value = "80%"

[[skill]]
title = "Product Design"
value = "90%"

[[skill]]
title = "Manufacturing Processes"
value = "75%"


############## Language config ##################
#################################################
[languages]
title = "Languages"
enabled = true
show_bar = true
show_value = true

[[language]]
title = "Telugu"
value = "100%"

[[language]]
title = "English"
value = "90%"

[[language]]
title = "Hindi"
value = "50%"
