############## Education config #################
#################################################
[[education]]
title = "Prasanthi Nikethan M.V.V.S Murthy ENG MED High School, Anakapalli"
timeline = "2008 - 2020"
description = "SSC - Andhra Pradesh - 10 CGPA"

[[education]]
title = "Rajiv Gandhi University of Knowledge Technology, Srikakulam"
timeline = "2020 - 2022"
description = "Pre University Course - 9.35 CGPA"

[[education]]
title = "International Institute of Information Technology, Hyderabad"
timeline = "2022 - Present"
description = "B.Tech in Computer Science & Engineering - 6.81 CGPA (current)"


############## Experience config ################
#################################################
[[experience]]
title = "Tech Team - Club Council & Student Life Committee (IIIT Hyderabad)"
timeline = "August 2023 – Present"
description = "Maintaining clubs websites and servers, Adding new features to improve user engagement and experience, providing technical support for club activities and events."

[[experience]]
title = "Web Admin (IT Office IIITH)"
timeline = "August 2023 – Present"
description = "Maintaining and updating university websites under the supervision of the IT Office, creating & designing new web pages for events and announcements."

[[experience]]
title = "Undergraduate Researcher (SERC lab, IIITH)"
timeline = "April 2024 - Present"
description = "Conducting research under Dr. Raman Saxena focusing on human-centered design and design thinking methodologies. Completed a summer project that provided valuable insights into gathering user opinions/problems on present existing Institute Management system and applying them to design effective, user-friendly solutions."

[[experience]]
title = "Software Intern (Virtual Labs)"
timeline = "January 2024 - April 2024"
description = "Collaborated on the development of a VS Code Web Extension for a Virtual Labs Authoring Environment using a tech stack that included TypeScript, Webpack, and various APIs. Engaged in continuous meetings with clients, honing my ability to interact effectively, gather valuable feedback, and understand the project process flow comprehensively"



############## Courses config ####################
#################################################
[courses]
title = "Courses"
enabled = true
show_bar = false
show_value = false

[[course]]
title = "Data Structures and Algorithms"

[[course]]
title = "Operating Systems and Networks"

[[course]]
title = "Introduction to Software Systems"

[[course]]
title = "Design and Analysis Software Systems"

[[course]]
title = "Algorithm Analysis and Design"

[[course]]
title = "Computer Organization and Architecture"

[[course]]
title = "Database Management System"

[[course]]
title = "Internet of Things"

[[course]]
title = "Intro to Information Security"

[[course]]
title = "Machine and Data Learning"

[[course]]
title = "Computer Graphics"

[[course]]
title = "Embeded Systems workshop"


############## achievements config ####################
#################################################
[achievements]
title = "Achievements"
enabled = true

[[achievement]]
title = "Bharat Intern Certification"
timeline = "January 2024"
description = "Received a certicate from bharat Intern for a virtual Intership program in which I built two websites based on FullStack Development."

[[achievement]]
title = "Study with US Certification"
timeline = "May 2022"
description = "Study With Us is an intiative from RGUKT students in AP where they offer different programming courses where I completed the C Programming Course."

[[achievement]]
title = "DevTown Certification in Web Development Bootcamp"
timeline = "May 2022"
description = "In the bootcamp, I completed the given tasks of builing a facebook clone and a netflix clone which gave me great experience of laerning web dev."

[[achievement]]
title = "Shape AI Certification for python and Cyber Security"
timeline = "June 2021"
description = "In the workshop, started with python and the flow of teaching ended with cyber security basics, I learnt very good basics from it and they provided me with a certificate after an exam."

[[achievement]]
title = "District Level Silver Medal in International Mathematics Olympiad"
timeline = "August 2016"
description = "Secured a silver medal in the International Mathematics Olympiad conducted at the district level after School level."

############## Language config ##################
#################################################
[languages]
title = "Languages"
enabled = true
show_bar = true
show_value = true

[[language]]
title = "English"
value = "100%"

[[language]]
title = "Telugu"
value = "100%"

[[language]]
title = "Hindi"
value = "75%"
