# https://ionic.io/ionicons
# <ion-icon name="[[name]]"></ion-icon>
# name = "https://example.com/"

logo-facebook = "https://www.facebook.com/charan.adari.9"
logo-twitter = "https://x.com/adari_charan"
logo-instagram = "https://www.instagram.com/cherry_babu2002/"
logo-linkedin = "https://www.linkedin.com/in/charan-adari-b3943926a/"
logo-github = "https://github.com/Charanadari"
# logo-dribbble = "https://dribbble.com/"
# logo-figma = "figma.com/"
# logo-youtube = "https://youtube.com/"
# logo-reddit = "https://www.reddit.com/"
# logo-discord = "https://discord.com/"
# logo-pinterest = "https://www.pinterest.com/"